[package]
name = "renderer"
version = "0.1.0"
authors = ["davidsullivan <touisbetterthanpi@gmail.com>"]

[dependencies]

sdl2 = "0.31.0"
rand = "0.5.5"
num = "0.2.0"
spin_sleep = "0.3.6"
stl-handler = {git = "https://github.com/SiliconLion/stl-handler.git"}
stl_io = "0.3.7"